---
- name: Verify
  hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - apache2
        - openssl

    - name: Check if security-headers.conf is present
      stat:
        path: "/etc/apache2/conf-available/security-headers.conf"
      register: sec_headers_file

    - name: Verify security-headers.conf installation
      assert:
        that:
        - "sec_headers_file.stat.exists"

    - name: Check if ssl-params.conf is present
      stat:
        path: "/etc/apache2/conf-available/ssl-params.conf"
      register: ssl_params_file

    - name: Verify ssl-params.conf installation
      assert:
        that:
          - "ssl_params_file.stat.exists"
